import type { RestaurantItem } from "@/src/features/listings/model/listings-store";

export const restaurants: RestaurantItem[] = [
  {
    id: "r1",
    name: "Sushi Sora",
    videoId: "finLqF_e0qc",
    mapQuery: "Fukuoka%20restaurants",
    icon: "youtube",
  },
  {
    id: "r2",
    name: "Pasta Fresca",
    videoId: "0II-qU0ADr4",
    mapQuery: "Fukuoka%30restaurants",
    icon: "youtube",
  },
  {
    id: "r3",
    name: "Taco Loco",
    videoId: "b4dPKoTRVTM",
    mapQuery: "Fukuoka%10restaurants",
    icon: "youtube",
  },
  {
    id: "r4",
    name: "Curry House",
    videoId: "R8Y0B49saOg",
    mapQuery: "Fukuoka%25restaurants",
    icon: "youtube",
  },
  {
    id: "r5",
    name: "Bistro Belle",
    videoId: "cCNlKOnGuBY",
    mapQuery: "Fukuoka%15restaurants",
    icon: "youtube",
  },
  {
    id: "r6",
    name: "Burger Hub",
    videoId: "tgOLRY0BPCg",
    mapQuery: "Fukuoka%20restaurants",
    icon: "youtube",
  },
  {
    id: "r7",
    name: "Noodle Nest",
    videoId: "1sQIR35maJo",
    mapQuery: "Fukuoka%30restaurants",
    icon: "youtube",
  },
  {
    id: "r8",
    name: "Tapas Bar",
    videoId: "GqP6CmHrEZU",
    mapQuery: "Fukuoka%10restaurants",
    icon: "youtube",
  },
  {
    id: "r9",
    name: "BBQ Pit",
    videoId: "RF1fqlIzay0",
    mapQuery: "Fukuoka%25restaurants",
    icon: "youtube",
  },
  {
    id: "r10",
    name: "Pho Garden",
    videoId: "nurVHIUMYUY",
    mapQuery: "Fukuoka%35restaurants",
    icon: "youtube",
  },
  {
    id: "r11",
    name: "Dim Sum Joy",
    videoId: "wcjc7YTkWWI",
    mapQuery: "Fukuoka%15restaurants",
    icon: "youtube",
  },
  {
    id: "r12",
    name: "Kebab King",
    videoId: "finLqF_e0qc",
    mapQuery: "Fukuoka%20restaurants",
    icon: "youtube",
  },
  {
    id: "r13",
    name: "Seafood Bay",
    videoId: "0II-qU0ADr4",
    mapQuery: "Fukuoka%30restaurants",
    icon: "youtube",
  },
  {
    id: "r14",
    name: "Steak Forge",
    videoId: "b4dPKoTRVTM",
    mapQuery: "Fukuoka%10restaurants",
    icon: "youtube",
  },
  {
    id: "r15",
    name: "Vegan Vibes",
    videoId: "finLqF_e0qc",
    mapQuery: "Fukuoka%25restaurants",
    icon: "youtube",
  },
  {
    id: "r16",
    name: "Ramen Lab",
    videoId: "1sQIR35maJo",
    mapQuery: "Fukuoka%35restaurants",
    icon: "youtube",
  },
  {
    id: "r17",
    name: "Paella Place",
    videoId: "R8Y0B49saOg",
    mapQuery: "Fukuoka%15restaurants",
    icon: "youtube",
  },
  {
    id: "r18",
    name: "Goulash Haus",
    videoId: "b4dPKoTRVTM",
    mapQuery: "Fukuoka%20restaurants",
    icon: "youtube",
  },
  {
    id: "r19",
    name: "Pierogi Point",
    videoId: "0II-qU0ADr4",
    mapQuery: "Fukuoka%30restaurants",
    icon: "youtube",
  },
  {
    id: "r20",
    name: "Ceviche Co.",
    videoId: "finLqF_e0qc",
    mapQuery: "Fukuoka%10restaurants",
    icon: "youtube",
  },
];
